### ISSUE TITLE
Key transformer

### ISSUE THREAD

**Issue by hivokas** [coderello/laravel-shared-data#11]
It would be handy to have an ability to specify the key transformer:
```php
SharedData::keyTransformer(function ($key) {
    return Str::camel($key);
});
```

So that:
```php
share(['auth_user' => auth()->user()]);
```
Will be transformed into:
```json
{
    "authUser": {
        "id": 1,
        "firstName": "Ilya",
        "lastName": "Sakovich"
    }
}
```

**Comment by klimov-paul** [comment]
I would say it is an unnecessary overcomplication.
If someone wishes to use camel case instead of snake case it is better to be changed outside `SharedData`.
Creating extra magic here will simply confuse developer.

**Comment by hivokas** [comment]
Well, agreed.
