### ISSUE TITLE
Erro with Laravel 8 + PHP 7.4: The directive name [] is not valid. Directive names must only contain alphanumeric characters and underscores.

### ISSUE THREAD

**Issue by silasrm** [coderello/laravel-shared-data#26]
After install on Laravel 8.0 + PHP 7.4:

`InvalidArgumentException 

  The directive name [] is not valid. Directive names must only contain alphanumeric characters and underscores.

  at vendor/laravel/framework/src/Illuminate/View/Compilers/BladeCompiler.php:681
`

Any idea?

**Comment by hivokas** [comment]
Hey @silasrm!
I assume you have an outdated config. Please ensure you have the same structure: https://github.com/coderello/laravel-shared-data/blob/3.0/config/shared-data.php
