### ISSUE TITLE
Nonce CSP is not supported

### ISSUE THREAD

**Issue by mariusaustr** [coderello/laravel-shared-data#29]
There is no way to use nonce content security policy, since `Coderello\SharedData\SharedData::render()` method returns `<script>` with no way to inject additional data.

```
public function render(): string
    {
        return '<script>'
            .'window["'.$this->getJsNamespace().'"]='.$this->toJson().';'
            .'window["sharedDataNamespace"]="'.$this->getJsNamespace().'";'
            .($this->getJsHelperEnabled() ? $this->getJsHelper().';' : '')
            .'</script>';
    }
```

I think either class constructor or render method could accept nonce value.

**Comment by hivokas** [comment]
Thanks, @mariusaustr! It makes sense.

I've published a new release to support that: https://github.com/coderello/laravel-shared-data/releases/tag/3.2.0
