### ISSUE TITLE
Make ServiceProvider Deferrable

### ISSUE THREAD

**Issue by klimov-paul** [coderello/laravel-shared-data#3]
`SharedDataServiceProvider` is better to be [deferrable](https://laravel.com/docs/5.8/providers#deferred-providers).
It should be loaded only when `\Coderello\SharedData\SharedData` is requested from DI container.

This will improve application performance for such requests as REST API and console commands.

Note that deferrable service provider definition has been changed in Laravel 5.8. It might be a BC-break change.

**Comment by hivokas** [comment]
Makes sense, fixed (#5)
