### ISSUE TITLE
Stable Release

### ISSUE THREAD

**Issue by hivokas** [coderello/laravel-shared-data#8]
I'm planning to publish a stable release.

Are there any breaking changes which should be done before this release?

**Comment by klimov-paul** [comment]
You may consider renaming `js_namespace` to `jsNamespace` at config:
https://github.com/coderello/laravel-shared-data/blob/master/config/shared-data.php#L15

**Comment by hivokas** [comment]
I think it's not a good idea. Because Laravel community uses snake case for config keys.

**Comment by klimov-paul** [comment]
OK, then it is ready for 1.0.0.

**Comment by hivokas** [comment]
Please, check my latest changes:
https://github.com/coderello/laravel-shared-data/commit/1b00097ff05f5d98bd78d2ee33e9df3191a21d85

**Comment by klimov-paul** [comment]
I would not extract separate method `hydrateConfig()`.
Other changes look fine.

**Comment by hivokas** [comment]
Well, I've published the release.
